### ISSUE TITLE
Improve the icon generator

### ISSUE THREAD

**Issue by danielthepope** [danielthepope/trntxt#25]
(Unplanned idea - need to do some research)
Use a JavaScript library to generate an SVG file (rather than using a base raster image and resizing it).
Convert the SVG to PNG to the requested size. See if it can be done antialiased.
And change the colour: blue is boring.

**Comment by Birch-san** [comment]
EaselJS is a good drawing library for JS. It was made by an old Flash dev who wanted to mimic Flash's drawing API.
Thanks to node-canvas, a [Node version of EaselJS](https://www.npmjs.com/package/node-easel) was built that can draw canvas without a DOM, outputting to a PNG.
