### ISSUE TITLE
web.config

### ISSUE THREAD

**Issue by aarongustafson** [danielthepope/trntxt#36]
Don’t forget the web.config file: https://a-k-apart.com/webconfigs/web.config.node.txt

**Comment by danielthepope** [comment]
Hi Aaron, my project is already successfully deployed on Azure as an App Service at http://trntxt.azurewebsites.net without a web.config.
I can add one if need be, but it looks like it's working fine without it. What do you think?

**Comment by danielthepope** [comment]
Never mind, done now.
