### ISSUE TITLE
Some issues preventing this from being a full PWA

### ISSUE THREAD

**Issue by omgmog** [danielthepope/trntxt#38]
According to the tests in Paul Kinlan's [_Progressive Web App Checklist_ bookmarklet](https://gist.github.com/PaulKinlan/ce7c707e4cb96c752816):

- [x] Manifest has been fetched
- [x] Site is on HTTPS
- [x] All assets are on https
- [x] Site has a canonical URL
- [x] Site manifest has theme_color
- [x] Site manifest has background_color
- [x] Site manifest has start_url
- [x] Site manifest has short_name
- [x] Site manifest has name
- [x] Site manifest has icons defined
- [x] Site manifest has 192px icon
- [x] Site is currently controlled by a service worker
- [x] Site is has a service worker registration
- [x] Site has cached data. Might work offline
- [x] All Requests made from the page are in the cache

**Comment by omgmog** [comment]
I think once all of these are fulfilled, Chrome on Android _can_ prompt to "Add to homescreen" automatically!

**Comment by danielthepope** [comment]
Nice checklist! Most of those seem easily fixable too 👍

**Comment by danielthepope** [comment]
Done! Just in time for Oreo to change how PWA icons look on the homescreen.
The service worker isn't exactly useful - that'll be another issue to fix.
