### ISSUE TITLE
Later trains

### ISSUE THREAD

**Issue by benfoxall** [danielthepope/trntxt#50]
Is there any way to request a next "page" of departures?

I just tried to use trntxt to find the last train on a route though couldn't do it.

**Comment by danielthepope** [comment]
Ah sorry Ben! From what I remember the National Rail API can provide another 2 hours of schedules, though I didn't make use of it (it was a separate API call). I'll try to get round to adding this when I find some free time 👍

**Comment by benfoxall** [comment]
Absolutely no apology necessary; trntxt is **awesome** exactly way it is :heart:. 

I just figured I'd log another use case while I remembered (I ended up using google directions today).

I could take a stab at making the change myself if you wanted?

**Comment by danielthepope** [comment]
Well, my super busy March has finished now, so I should be able to give it a go this month

**Comment by danielthepope** [comment]
Right then, trntxt currently has a limit of displaying up to 10 results up to 2 hours in the future.

I had a go with this last night (to get all results within the next 4 hours) and in some cases there were too many results for 1 page!

I'm going to break this down into 2 parts:
- [ ] Return a maximum of 10 results within 4 hours.
- [ ] Add paging, e.g. `trntxt.uk/pad/rdg/2` for a second page of results, when there are more than 10 results within the next 4 hours.

**Comment by danielthepope** [comment]
Looks like I never bothered with paging. I'm now just returning all the results the API can get.
