### ISSUE TITLE
Invalid Site Description?

### ISSUE THREAD

**Issue by MagicAndi** [danielthepope/trntxt#52]
Just to make a comment regarding your site's description 'Train Text: a data-friendly UK train times site'. The search doesn't appear to work for train stations in Northern Ireland (i.e. stations like Belfast Central and Coleraine). I've checked the National Rail timetable search at [https://www.nationalrail.co.uk/times_fares/ldb.aspx](https://www.nationalrail.co.uk/times_fares/ldb.aspx), and while the search here will prompt you with the station names, it then errors when attempting to search for the relevant timetable.  This suggests that the issue is with the underlying National Rail 'Darwin' API.

Possibly you could update your title to be 'a data-friendly GB train times site', or otherwise indicate that NI timetables are unavailable? Thanks.

**Comment by danielthepope** [comment]
Thanks for pointing this out @MagicAndi - I of all people should have spotted that, especially since I made this [stupid little hack](https://danielthepope.github.io/whatistheuk/).

The URL will remain trntxt.uk though ;)
